name: Unit Test
on: [push, pull_request]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules/.cache
          key: ${{ runner.OS }}-test-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-test-
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'coverage/lcov.info'
      - name: Run Coveralls
        uses: coverallsapp/github-action@v2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: 'coverage/lcov.info'
          format: 'lcov'
